### ISSUE TITLE
Explicit delete confirmation action

### ISSUE THREAD

**Issue by bonominijl** [astronomer/astronomer-ee#127]
As a user, I want to ensure deployments are not erroneously deleted through the UI. 

Deleting a deployment should prompt the user for the deployment name to be manually typed in, prior to confirming the delete action. 

This is similar to deleting services in GCP or other cloud tools, requiring you to type in the service name before you're able to confirm.

**Comment by ryw** [comment]
Issue moved to [astronomer/astronomer #176](https://github.com/astronomer/astronomer/issues/176) via [**ZenHub**](https://www.zenhub.com/)
